// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9nmL6xtitpfQHTI84RF1tpSPiCC3JM2o',
    appId: '1:786766368924:web:4aebf7519ff7523224dd59',
    messagingSenderId: '786766368924',
    projectId: 'vdoc-b4565',
    authDomain: 'vdoc-b4565.firebaseapp.com',
    storageBucket: 'vdoc-b4565.appspot.com',
    measurementId: 'G-C8HYK1VPW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMP37n5EJOOOWYpKQptB-9HLOjtTohdNY',
    appId: '1:786766368924:android:1aff3bc2c13f6e9524dd59',
    messagingSenderId: '786766368924',
    projectId: 'vdoc-b4565',
    storageBucket: 'vdoc-b4565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXnWCvp5RKTWOqH-1HsYEcT_Nv4KcnMIg',
    appId: '1:786766368924:ios:0a61a830e0b2a37a24dd59',
    messagingSenderId: '786766368924',
    projectId: 'vdoc-b4565',
    storageBucket: 'vdoc-b4565.appspot.com',
    iosBundleId: 'com.example.vdoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXnWCvp5RKTWOqH-1HsYEcT_Nv4KcnMIg',
    appId: '1:786766368924:ios:0a61a830e0b2a37a24dd59',
    messagingSenderId: '786766368924',
    projectId: 'vdoc-b4565',
    storageBucket: 'vdoc-b4565.appspot.com',
    iosBundleId: 'com.example.vdoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9nmL6xtitpfQHTI84RF1tpSPiCC3JM2o',
    appId: '1:786766368924:web:9e876c857423217724dd59',
    messagingSenderId: '786766368924',
    projectId: 'vdoc-b4565',
    authDomain: 'vdoc-b4565.firebaseapp.com',
    storageBucket: 'vdoc-b4565.appspot.com',
    measurementId: 'G-K0R898QJPP',
  );
}
